CREATE TABLE assign
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id_id BIGINT,
    CONSTRAINT pk_assign PRIMARY KEY (id)
);

CREATE TABLE batch
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url       VARCHAR(255),
    is_active BOOLEAN,
    CONSTRAINT pk_batch PRIMARY KEY (id)
);

CREATE TABLE history
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_history PRIMARY KEY (id)
);

CREATE TABLE history_item_ids
(
    history_id BIGINT NOT NULL,
    item_ids   BIGINT
);

CREATE TABLE history_item_names
(
    history_id     BIGINT NOT NULL,
    item_names     VARCHAR(255),
    item_names_key BIGINT NOT NULL,
    CONSTRAINT pk_history_itemnames PRIMARY KEY (history_id, item_names_key)
);

CREATE TABLE markup
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     BIGINT,
    batch_id_id BIGINT,
    CONSTRAINT pk_markup PRIMARY KEY (id)
);

CREATE TABLE markup_elements
(
    markup_id    BIGINT       NOT NULL,
    elements     VARCHAR(255),
    elements_key VARCHAR(255) NOT NULL,
    CONSTRAINT pk_markup_elements PRIMARY KEY (markup_id, elements_key)
);

CREATE TABLE my_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255),
    password VARCHAR(255),
    role     SMALLINT,
    CONSTRAINT pk_my_user PRIMARY KEY (id)
);

CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

CREATE TABLE task_row_from_batch
(
    task_id            BIGINT       NOT NULL,
    row_from_batch     VARCHAR(255),
    row_from_batch_key VARCHAR(255) NOT NULL,
    CONSTRAINT pk_task_rowfrombatch PRIMARY KEY (task_id, row_from_batch_key)
);

ALTER TABLE assign
    ADD CONSTRAINT FK_ASSIGN_ON_BATCHID FOREIGN KEY (batch_id_id) REFERENCES batch (id);

ALTER TABLE markup
    ADD CONSTRAINT FK_MARKUP_ON_BATCHID FOREIGN KEY (batch_id_id) REFERENCES batch (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_BATCHID FOREIGN KEY (batch_id_id) REFERENCES batch (id);

ALTER TABLE history_item_ids
    ADD CONSTRAINT fk_history_itemids_on_history FOREIGN KEY (history_id) REFERENCES history (id);

ALTER TABLE history_item_names
    ADD CONSTRAINT fk_history_itemnames_on_history FOREIGN KEY (history_id) REFERENCES history (id);

ALTER TABLE markup_elements
    ADD CONSTRAINT fk_markup_elements_on_markup FOREIGN KEY (markup_id) REFERENCES markup (id);

ALTER TABLE task_row_from_batch
    ADD CONSTRAINT fk_task_rowfrombatch_on_task FOREIGN KEY (task_id) REFERENCES task (id);